### ISSUE TITLE
Update to work with current eslint

### ISSUE THREAD

**Issue by elbotho** [ory-am/eslint-config-ory-am#3]
```
npm WARN eslint-config-ory-am@2.0.0 requires a peer of eslint@>= 2.5.0 < 3 but none was installed.
```

Current version of `eslint` is at `3.0.0`

**Comment by inyono** [comment]
Thanks for reporting this issue, @elbotho. Will probably do this today or tomorrow. If you use NPM 3 (i.e. at least Node v4), it _should_ work anyway (with warnings).

**Comment by inyono** [comment]
Will publish this on NPM later today after reviewing our other projects (and after the football game ⚽)
